version: 2
jobs:
  build:
    working_directory: ~/chanman-frontend
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - restore_cache:
          keys:
            - chanman-cache-{{ checksum "yarn.lock" }}

      - run:
          name: Install packages
          command: NODE_ENV=development yarn install

      - save_cache:
          key: chanman-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Build main project
          command: yarn build

      - run:
          name: Login to Docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Create Docker image
          command: docker build -t loveit/chanman-frontend .

      - run:
          name: Push updated Docker image
          command: docker push loveit/chanman-frontend